In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

In [4]:
df1 = pd.read_csv("train.csv")
df1.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [5]:
df1.columns

Index(['ID', 'A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score',
       'A6_Score', 'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age',
       'gender', 'ethnicity', 'jaundice', 'austim', 'contry_of_res',
       'used_app_before', 'result', 'age_desc', 'relation', 'Class/ASD'],
      dtype='object')

In [6]:
df1["age"] = df1["age"].astype(int)
df1.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [7]:
df1.isnull().sum()

ID                 0
A1_Score           0
A2_Score           0
A3_Score           0
A4_Score           0
A5_Score           0
A6_Score           0
A7_Score           0
A8_Score           0
A9_Score           0
A10_Score          0
age                0
gender             0
ethnicity          0
jaundice           0
austim             0
contry_of_res      0
used_app_before    0
result             0
age_desc           0
relation           0
Class/ASD          0
dtype: int64

In [8]:
for col in df1.columns:
    num_cols = ["ID", "age", "result"]
    if col not in num_cols:
        print(col, df1[col].unique())
        print("-"*50)

A1_Score [1 0]
--------------------------------------------------
A2_Score [0 1]
--------------------------------------------------
A3_Score [1 0]
--------------------------------------------------
A4_Score [0 1]
--------------------------------------------------
A5_Score [1 0]
--------------------------------------------------
A6_Score [0 1]
--------------------------------------------------
A7_Score [1 0]
--------------------------------------------------
A8_Score [0 1]
--------------------------------------------------
A9_Score [1 0]
--------------------------------------------------
A10_Score [1 0]
--------------------------------------------------
gender ['f' 'm']
--------------------------------------------------
ethnicity ['?' 'White-European' 'Middle Eastern ' 'Pasifika' 'Black' 'Others'
 'Hispanic' 'Asian' 'Turkish' 'South Asian' 'Latino' 'others']
--------------------------------------------------
jaundice ['no' 'yes']
--------------------------------------------------
austim ['no' 'yes']
--------------------------------------------------
contry_of_res ['Austria' 'India' 'United States' 'South Africa' 'Jordan'
 'United Kingdom' 'Brazil' 'New Zealand' 'Canada' 'Kazakhstan'
 'United Arab Emirates' 'Australia' 'Ukraine' 'Iraq' 'France' 'Malaysia'
 'Viet Nam' 'Egypt' 'Netherlands' 'Afghanistan' 'Oman' 'Italy'
 'AmericanSamoa' 'Bahamas' 'Saudi Arabia' 'Ireland' 'Aruba' 'Sri Lanka'
 'Russia' 'Bolivia' 'Azerbaijan' 'Armenia' 'Serbia' 'Ethiopia' 'Sweden'
 'Iceland' 'Hong Kong' 'Angola' 'China' 'Germany' 'Spain' 'Tonga'
 'Pakistan' 'Iran' 'Argentina' 'Japan' 'Mexico' 'Nicaragua' 'Sierra Leone'
 'Czech Republic' 'Niger' 'Romania' 'Cyprus' 'Belgium' 'Burundi'
 'Bangladesh']
--------------------------------------------------
used_app_before ['no' 'yes']
--------------------------------------------------
age_desc ['18 and more']
--------------------------------------------------
relation ['Self' 'Relative' 'Parent' '?' 'Others' 'Health care professional']
--------------------------------------------------
Class/ASD [0 1]
--------------------------------------------------

In [9]:
df2 = df1.drop(columns=["ID", "age_desc","relation","ethnicity","contry_of_res"])

In [10]:
df2.shape

(800, 17)

In [11]:
df2.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,jaundice,austim,used_app_before,result,Class/ASD
0,1,0,1,0,1,0,1,0,1,1,38,f,no,no,no,6.351166,0
1,0,0,0,0,0,0,0,0,0,0,47,m,no,no,no,2.255185,0
2,1,1,1,1,1,1,1,1,1,1,7,m,no,yes,no,14.851484,1
3,0,0,0,0,0,0,0,0,0,0,23,f,no,no,no,2.276617,0
4,0,0,0,0,0,0,0,0,0,0,43,m,no,no,no,-4.777286,0

In [12]:
print(df2['gender'].unique())
df2['gender'] = df2['gender'].replace({
    'f': 1, 'female': 1,
    'm': 0, 'male': 0
})
df2['jaundice'] = df2['jaundice'].replace({
    'yes': 1, 
    'no': 0
})
df2['austim'] = df2['austim'].replace({
    'yes': 1, 
    'no': 0
})
df2['used_app_before'] = df2['used_app_before'].replace({
    'yes': 1, 
    'no': 0
})

['f' 'm']

C:\Users\nehar\AppData\Local\Temp\ipykernel_43188\763957283.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['gender'] = df2['gender'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_43188\763957283.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['jaundice'] = df2['jaundice'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_43188\763957283.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['austim'] = df2['austim'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_43188\763957283.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['used_app_before'] = df2['used_app_before'].replace({

In [13]:
df2.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,jaundice,austim,used_app_before,result,Class/ASD
0,1,0,1,0,1,0,1,0,1,1,38,1,0,0,0,6.351166,0
1,0,0,0,0,0,0,0,0,0,0,47,0,0,0,0,2.255185,0
2,1,1,1,1,1,1,1,1,1,1,7,0,0,1,0,14.851484,1
3,0,0,0,0,0,0,0,0,0,0,23,1,0,0,0,2.276617,0
4,0,0,0,0,0,0,0,0,0,0,43,0,0,0,0,-4.777286,0

In [14]:
X= df2.drop('Class/ASD',axis='columns')
X

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,jaundice,austim,used_app_before,result
0,1,0,1,0,1,0,1,0,1,1,38,1,0,0,0,6.351166
1,0,0,0,0,0,0,0,0,0,0,47,0,0,0,0,2.255185
2,1,1,1,1,1,1,1,1,1,1,7,0,0,1,0,14.851484
3,0,0,0,0,0,0,0,0,0,0,23,1,0,0,0,2.276617
4,0,0,0,0,0,0,0,0,0,0,43,0,0,0,0,-4.777286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0,1,0,0,0,0,0,0,1,1,16,0,0,0,0,12.999501
796,0,1,1,0,0,1,0,1,1,1,20,0,0,0,0,13.561518
797,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2.653177
798,0,0,0,0,0,0,0,0,0,0,16,1,0,0,0,9.069342
799,0,1,0,0,0,0,0,0,0,0,46,1,0,0,1,2.243304

In [15]:
y = df2['Class/ASD']
y

0      0
1      0
2      1
3      0
4      0
      ..
795    0
796    0
797    0
798    0
799    0
Name: Class/ASD, Length: 800, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [17]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [18]:
model.fit(X_train,y_train)

GaussianNB()

In [19]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.84821429, 0.80357143, 0.78571429, 0.82142857, 0.875     ])

In [20]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [21]:
model.score(X_test, y_test)

0.85

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [23]:
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier

In [24]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=1000),
    "SVM": SVC(kernel='rbf', probability=True)
}
kf = KFold(n_splits=8, shuffle=True, random_state=42)
for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=kf, scoring='accuracy')
    print(f"{name} - Mean Accuracy: {scores.mean():.4f} | Std Dev: {scores.std():.4f}")

Logistic Regression - Mean Accuracy: 0.8563 | Std Dev: 0.0346
Random Forest - Mean Accuracy: 0.8450 | Std Dev: 0.0456
SVM - Mean Accuracy: 0.8662 | Std Dev: 0.0308

In [25]:
from sklearn.tree import DecisionTreeClassifier
base_estimator = DecisionTreeClassifier()
bagging_model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100, random_state=42)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=1000, random_state=42),
    "SVM": SVC(kernel='rbf', probability=True),
    "Bagging (DT base)": bagging_model
}

kf = KFold(n_splits=6, shuffle=True, random_state=42)

for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=kf, scoring='accuracy')
    print(f"{name} - Mean Accuracy: {scores.mean():.4f} | Std Dev: {scores.std():.4f}")

Logistic Regression - Mean Accuracy: 0.8587 | Std Dev: 0.0322
Random Forest - Mean Accuracy: 0.8488 | Std Dev: 0.0355
SVM - Mean Accuracy: 0.8650 | Std Dev: 0.0251
Bagging (DT base) - Mean Accuracy: 0.8413 | Std Dev: 0.0397

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, KFold


decision_tree = DecisionTreeClassifier(random_state=42)


bagging_model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100, random_state=42)

models = {
    "Decision Tree": decision_tree,
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=1000, random_state=42),
    "SVM": SVC(kernel='rbf', probability=True),
    "Bagging (DT base)": bagging_model
}


kf = KFold(n_splits=6, shuffle=True, random_state=42)


for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=kf, scoring='accuracy')
    print(f"{name} - Mean Accuracy: {scores.mean():.4f} | Std Dev: {scores.std():.4f}")

Decision Tree - Mean Accuracy: 0.8112 | Std Dev: 0.0266
Logistic Regression - Mean Accuracy: 0.8587 | Std Dev: 0.0322
Random Forest - Mean Accuracy: 0.8488 | Std Dev: 0.0355
SVM - Mean Accuracy: 0.8650 | Std Dev: 0.0251
Bagging (DT base) - Mean Accuracy: 0.8413 | Std Dev: 0.0397

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, KFold


decision_tree = DecisionTreeClassifier(random_state=42)


bagging_dt = BaggingClassifier(
    estimator=DecisionTreeClassifier(),  
    n_estimators=100,                   
    random_state=42
)


models = {
    "Decision Tree (Standalone)": decision_tree,
    "Bagging (DT Base Estimator)": bagging_dt,
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=1000, random_state=42),
    "SVM": SVC(kernel='rbf', probability=True)
}


kf = KFold(n_splits=6, shuffle=True, random_state=42)


for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=kf, scoring='accuracy')
    print(f"{name} - Mean Accuracy: {scores.mean():.4f} | Std Dev: {scores.std():.4f}")

Decision Tree (Standalone) - Mean Accuracy: 0.8112 | Std Dev: 0.0266
Bagging (DT Base Estimator) - Mean Accuracy: 0.8413 | Std Dev: 0.0397
Logistic Regression - Mean Accuracy: 0.8587 | Std Dev: 0.0322
Random Forest - Mean Accuracy: 0.8488 | Std Dev: 0.0355
SVM - Mean Accuracy: 0.8650 | Std Dev: 0.0251

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


df = pd.read_csv("train.csv")


df = df.drop(columns=["ID", "age_desc"])


X = df.drop(columns=["Class/ASD"])
y = df["Class/ASD"]


categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')


preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)


pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

param_grid = {
    "classifier__n_estimators": [100, 200, 300],
    "classifier__max_depth": [None, 10, 20],
    "classifier__min_samples_split": [2, 5],
    "classifier__min_samples_leaf": [1, 2]
}

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)


best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Best Accuracy:", accuracy)
print("Best Parameters:", grid_search.best_params_)

Best Accuracy: 0.8625
Best Parameters: {'classifier__max_depth': 10, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 5, 'classifier__n_estimators': 300}

In [28]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X, y)
model.score(X,y)

ValueError: could not convert string to float: 'f'